### ISSUE TITLE
"frame.Frame.parseHeader: The flac library test cases do not yet include any audio files with block size 192."

### ISSUE THREAD

**Issue by lpar** [mewkiz/flac#55] opened 2023-01-08 21:44 UTC
>frame.Frame.parseHeader: The flac library test cases do not yet include any audio files with block size 192. If possible please consider contributing this audio sample to improve the reliability of the test cases.

Hit this message processing a file. I'd be happy to provide the file, but it's copyrighted material ripped from a CD. Would that work to extract the appropriate test blocks?

**Comment by mewmew** [comment] 2023-01-09 04:58
> Hit this message processing a file. I'd be happy to provide the file, but it's copyrighted material ripped from a CD. Would that work to extract the appropriate test blocks?

Hej @lpar,

Thanks for reaching out to us! I think all our test cases are currently Create Commons licensed or released within the Public Domain.

As to the extent copyright law, my insights are fortunately limited.

I think we can close this issue as a the IETF test case suit also included samples with block size 192. Ref: https://github.com/mewkiz/flac/issues/54#issuecomment-1267581410

That way we can resolve the issue of copyright.

Wish you all the best @lpar and a great year to come!

**Comment by mewmew** [comment] 2023-01-09 04:59
Closing as duplicate of https://github.com/mewkiz/flac/issues/54#issuecomment-1267581410 (which also contains test samples for block size 192).

Cheers,
Robin

**Closed by mewmew** 2023-01-09 04:59 UTC
Labels: duplicate
